from Common.utils.SwaggerURL import SwaggerURL

SwaggerURL.URL_COUNT = {
    "POST:http://www.lieluobo.testing/api/biz/resume/groups/addTo": 1,
    "POST:/resume/extractor": 1,
    "POST:": 1,
    "POST:/token/upload": 1,
    "POST:/resume": 1,
    "POST:/operation/search": 1,
    "POST:/resume/extractorAndSave": 1,
    "POST:http://www.lieluobo.testing/api/biz/resume/groups/addToList": 1,
    "POST:http://www.lieluobo.testing/api/biz/resume/search": 1,
    "POST:http://www.lieluobo.testing/api/biz/resume/{id}/reportDownload": 1,
    "POST:http://www.lieluobo.testing/api/biz/project/checkResumeRepeat": 1,
    "POST:http://www.lieluobo.testing/api/biz/project/cRecommendProjects": 1,
    "POST:http://www.lieluobo.testing/api/biz/project/getOneAll": 1,
    "POST:http://www.lieluobo.testing/api/biz/resume/id/{id}": 1,
    "POST:http://www.lieluobo.testing/api/biz/reportTemplates/search": 1,
    "POST:http://www.lieluobo.testing/api/biz/common/qiniu/token": 1,
    "POST:http://www.lieluobo.testing/api/biz/resume/remark": 1,
    "POST:http://www.lieluobo.testing/api/biz/token/upload": 1,
    "POST:http://file.testing.lieluobo.net": 1,
    "POST:http://www.lieluobo.testing/api/biz/attachment": 1,
    "POST:/resume/search": 1,
    "POST:/report/id": 1,
    "POST:/resume/id/{id}": 1,
    "POST:/report": 1,
    "POST:/project/recommendToCw": 1,
    "POST:/project/recommendProjects": 1,
    "POST:/account/pwd": 1,
    "POST:/account/saveCSubscription": 1,
    "POST:/todo/list": 1,
    "POST:/project/subscriber/cw/add": 1,
    "POST:/project/subscriberProjects": 1,
    "POST:/todo": 1,
    "POST:/project/remark": 1,
    "POST:/project/remarks": 1,
    "POST:/project/c/indexProjects": 1,
    "GET:http://crm.lieluobo.testing/api/biz/specialEvent/list": 1,
    "POST:/specialEvent/copy/{id}": 1,
    "POST:/specialEvent/delete/{id}": 1,
    "POST:/specialEvent/save": 1,
    "POST:http://crm.lieluobo.testing/api/biz/specialEvent/delete/": 1,
    "POST:http://www.lieluobo.testing/api/biz/todo/list": 1,
    "POST:/project/projectListStat": 1,
    "POST:/project/unProjectAttention": 1,
    "POST:/project/projectAttention": 1,
    "POST:/project/projectAttentions": 1,
    "POST:/project/recentVisitedProjects": 1
}
SwaggerURL.sync_to_yoda()
